---
abstract: 'personal distributed reactive automation'
author:
  - 'Alex White <VVu@geekfarm.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300001, CPAN::Meta::Converter version 2.112621'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: wubot
recommends:
  AnyEvent::IRC::Client: 0
  AnyEvent::XMPP::Client: 0
  Astro::MoonPhase: 0
  Astro::Sunrise: 0
  Data::ICal: 0
  Data::ICal::Entry::Alarm::Audio: 0
  Data::ICal::Entry::Alarm::Display: 0
  Data::ICal::Entry::Event: 0
  Date::ICal: 0
  Device::SerialPort: 0
  Growl::Tiny: 0
  HTML::Strip: 0
  HTML::TableExtract: 0
  HTML::TokeParser::Simple: 0
  Mail::MboxParser: 0
  Maildir::Lite: 0
  Net::TiVo: 0
  Net::Twitter::Lite: 0
  RRD::Simple: 0
  RRDs: 0
  URI::Find: 0
  WWW::LongURL: 0
  XML::Atom::SimpleFeed: 0
  XML::Feed: 0
  XML::RSS: 0
  XML::Simple: 0
  XML::Twig: 0
requires:
  AnyEvent: 0
  AnyEvent::Watchdog: 0
  AnyEvent::Watchdog::Util: 0
  Benchmark: 0
  Capture::Tiny: 0
  Carp: 0
  Class::Load: 0
  DBD::SQLite: 0
  DBI: 0
  Date::Manip: 0
  DateTime: 0
  Devel::StackTrace: 0
  Digest::MD5: 0
  Encode: 0
  English: 0
  ExtUtils::MakeMaker: 0
  Fcntl: 0
  File::Basename: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  File::chdir: 0
  FileHandle: 0
  FindBin: 0
  Getopt::Long: 0
  HTTP::Message: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  Log::Log4perl: 0
  MIME::Base64: 0
  MIME::Entity: 0
  Mojo::Base: 0
  Moose: 0
  Moose::Role: 0
  POSIX: 0
  SQL::Abstract: 0
  Scalar::Util: 0
  Storable: 0
  Sys::Hostname: 0
  Term::ANSIColor: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::Mojo: 0
  Test::More: 0
  Test::Routine: 0
  Text::Template: 0
  URI::Escape: 0
  YAML: 0
  YAML::XS: 0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  repository: http://github.com/wu/wubot
version: 0.3.4
